### PR TITLE
Fix SASS partial live reloading

### LINKED ISSUE #1631: Stylesheets not updating in middleman v4
Stylesheet partials aren't being updated when making changes.
If I change them to normal stylesheets (remove the underscore), everything works well

### PR DESCRIPTION
**Pull request by johnnyshields**
Fixes #1631, #1627

In SourceWatcher, add a subroutine to find files which should be considered "also dirty" when a given file is touched.

### CODE REVIEW

File: middleman-core/lib/middleman-core/sources/source_watcher.rb [hunk 1]
```diff
@@ -222,6 +222,8 @@ def on_listener_change(modified, added, removed)
 
       return if updated.empty? && removed.empty?
 
+      updated |= find_related_files(updated + removed)
```
Comment (tdreyno) [inline middleman-core/lib/middleman-core/sources/source_watcher.rb]: Should this be `||=`

**Comment by tdreyno** [comment]
Hi @johnnyshields, thanks for debugging this. I'm going to try to take a slightly more holistic approach that handles all partials, not just Sass. I'll let you know in a few if it makes any sense

**Comment by tdreyno** [comment]
Actually, merging this as a great starting place.

**Comment by tdreyno** [comment]
@johnnyshields Can you verify https://github.com/middleman/middleman/commit/4594f46fb8ca8227e50e51a9706224cdd1ea5397 didn't break your fix?

**Comment by johnnyshields** [comment]
@tdreyno I can't run master as Ruby-SASSC is still broken. It looks like it should work tho.

**Comment by johnnyshields** [comment]
Spoke too soon, you fixed it! Thanks.

**Comment by johnnyshields** [comment]
@tdreyno your commit is broken:
1. `File.extname` includes the period, so you need to use this glob:  "**/[^_]*#{File.extname(file)}"
2. Even after fixing #1, I can't get SASS partials to load (please investigate).
3. Not such a big deal but did you consider that SCSS and SASS can be embedded inside each other? Also future versions of SASS will allow embedding CSS.
4. Note that SASS can embed files even if _ is not used. I tested this on your branch and it works, though I'm not sure why it works exactly--probably the partial hack is not needed for that case.

**Comment by tdreyno** [comment]
Test-only PRs are very welcome and can always help get your specific use-case implemented.

Try now, rewrote with even larger scope and some basic RSpecs.

**Comment by equinusocio** [comment]
Any update???
